spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///blog?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&nullCatalogMeansCurrent=true&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  redis:
    #超时时间
    timeout: 1000ms
    #服务器地址
    host: 127.0.0.1
    #服务器端口
    port: 6379
    #数据库
    database: 0
    #密码
    #password: root
#    lettuce:
#      pool:
#        #最大连接数，默认8
#        max-active: 1024
#        #最大连接阻塞等待时间，默认-1
#        max-wait: 10000ms
#        #最大空闲连接
#        max-idle: 200
#        #最小空闲连接
#        min-idle: 5
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.weblogtest.pojo
mybatis-plus:
  type-enums-package: com.example.weblogtest.Enum
pagehelper:
  #指定数据库，不指定的话会默认自动检测数据库的类型
  helper-dialect: mysql
  #是否启动分页合理化，如果启用，当pagemuns<1时，会自动查询第一页的数据，当pagenum>page时，自动查询最后一页
  #不启动时，以上两种情况都会返回null
  reasonable: true
  #默认为false，分页插件会从查询方法的参数值中，自动根据上面params配置的字段中取值，查找到合适的值时就会分页
  support-methods-arguments: true
logging:
  level:
    com.example.weblogtest.mapper: trace

